### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by dreamcat4** [cryinkfly/SOLIDWORKS-Linux-Wine-Version-#2]
Lol...
Really appreciate this. The solidworks is something that can be had sometimes on student license, or other institutional arrangement. So it's great to have as a possiblilty on linux.

Of course solidworks (as a cad program) has it's own set of issues. But it's great that you will try to help put together guides and information, and describe any bugs here. So that people knows about it.

Many thanks

**Comment by cryinkfly** [comment]
I use for my tests the Maker-License of SOLIDWORKS and I hope that I also get to work this program on Linux like as Autodesk Fusion 360. 😊

So can I help all people’s they will use this. 👌
