### ISSUE TITLE
Installation hangs up - VBA 7.1 (kb2783832) *solved*

### ISSUE THREAD

**Issue by cryinkfly** [cryinkfly/SOLIDWORKS-Linux-Wine-Version-#3]
### The problem at the time is, that the installation hangs up!

![Installation](https://user-images.githubusercontent.com/79079633/118714939-4a02dd80-b823-11eb-8bf7-407804ca0ea1.png)

> 019c:fixme:wininet:InternetSetFilePointer (00000004 0 00000000 0 1): stub
019c:fixme:wininet:InternetSetOptionW INTERNET_OPTION_SEND/RECEIVE_TIMEOUT/DATA_SEND_TIMEOUT 25000
019c:fixme:wininet:InternetSetFilePointer (00000004 0 00000000 0 1): stub

**Comment by cryinkfly** [comment]
Ok I have found this one:

https://forum.solidworks.com/thread/106830

**Comment by cewbdex** [comment]
Have you tried installing the executable manually? If I remember correctly I tried, but it errorred, but I did not manage to get as far as you. I was thinking of putting the product key to registry prior installation, so less pain in using that window is involved. Would you mind contacting via some instant messager?

**Comment by cryinkfly** [comment]
I have tested the installation of VBA 7.1 manually with a workaround from the support of SOLIDWORKS, but this solution doesn’t work for me.

What do you mean with putting the product key to registry prior installation? 😊

Which instant messager? 😅 Zoom or what?

**Comment by cryinkfly** [comment]
Did you mean this one here: https://forum.solidworks.com/thread/230350

**Comment by poohzaza166** [comment]
have you install ie8

**Comment by cryinkfly** [comment]
Yes I have also tested this with ie8, but the problem is the vba 7.1 😕

**Comment by poohzaza166** [comment]
try installing vb6 in wine tricks and vcrun6 because you are stuck on visual basic because excel and word support in solidwork

**Comment by cryinkfly** [comment]
Yes I know, but vb6 and vcrun6 are to old for this one. :-(

**Comment by cryinkfly** [comment]
I tried but it crashed immediately when I will install this with the msi installers.

**Comment by poohzaza166** [comment]
wine version?

**Comment by cryinkfly** [comment]
My wine version is 6.14. :+1: 

>  i think you need to copy the dll manually

This is a good idea, but also difficult. :-(

**Comment by Dyllan2000alfa** [comment]
Currently trying to figure out why the installer isn't starting on my laptop, but in the mean time I extracted the vba 7.1 msi file and setup the dll's in the structure that there installed to make manual dll installation easier. I attached a zip with it if anyone wants to see if a manual install fixes the problem

[vba7.1.zip](https://github.com/cryinkfly/SOLIDWORKS-Linux-Wine-Version-/files/7035852/vba7.1.zip)

**Comment by poohzaza166** [comment]
> Currently trying to figure out why the installer isn't starting on my laptop, but in the mean time I extracted the vba 7.1 msi file and setup the dll's in the structure that there installed to make manual dll installation easier. I attached a zip with it if anyone wants to see if a manual install fixes the problem
> 
> [vba7.1.zip](https://github.com/cryinkfly/SOLIDWORKS-Linux-Wine-Version-/files/7035852/vba7.1.zip)

did you install geko and wine from wine hq or just from your distro

**Comment by Dyllan2000alfa** [comment]
wine was installed from wine hq, no idea about geko. If I remember correctly wine just asked if I wanted to install geko after the solidworks install was started

**Comment by Zorgodon** [comment]
Still no solution in sight...

**Comment by cryinkfly** [comment]
Unfortunately, it still takes a while, but at least I managed to get two other CAD programs running! 😉

- https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-
- https://github.com/cryinkfly/Rhino-3D---Linux-Wine-Version-

**Comment by cryinkfly** [comment]
I'm going to try something different.

![Bildschirmfoto_2021-09-23_14-40-09](https://user-images.githubusercontent.com/79079633/134508345-a5c301ad-643c-4e2e-9962-79e71e0a63ce.png)

... and then I make a upgrade to a newer version!

**Comment by Dyllan2000alfa** [comment]
Think I fixed the VBA 7.1 (kb2783832) issue. I was able to extract the msp file, it contained a single dll specifically VBE7.DLL I replaced the dll of the same name that was in the vba7 msi file and the solidworks installer continued without issue. I attached an updated zip file if someone else wants to test it. All you need to do is copy the contents of the zip to the wine prefix solidworks is in and all the vba7 files for English will be installed.
[Uploading vba7.1.zip…]()

**Comment by cryinkfly** [comment]
Okay I'll check it out tonight! :1st_place_medal:

**Comment by Dyllan2000alfa** [comment]
Hopefully it works, I tried it again this morning with a new wine prefix and it's not working, though the original wine prefix I got it working on had no issues.

**Comment by cryinkfly** [comment]
I have tested this on my system, but I doesn't work for me! 🙁

![Bildschirmfoto_2021-09-30_17-35-13](https://user-images.githubusercontent.com/79079633/135486478-0f970d90-ba5c-43a0-a8f1-cbecb6e6e801.png)

**Comment by Dyllan2000alfa** [comment]
Okay figured out what I did that made it work and can now recreate it working in a new wine prefix. Dragging the files from the zip I made to the C drive does install VBA, but solidworks doesn't think it installs. So after copying the files I ran this command "msiexec /p vba71-kb2783832-x64.msp REINSTALL=ALL REINSTALLMODE=omus /qn" This has the opposite effect where solidworks thinks VBA is installed, but VBA isn't actually installed. So by combining these two I can install VBA and make sure solidworks knows VBA is installed.

**Comment by cryinkfly** [comment]
### Okay I have tested this now and it works for me!!! :+1: 

![Bildschirmfoto_2021-10-02_19-33-57](https://user-images.githubusercontent.com/79079633/135727020-0e8b75b2-1e5e-4da6-9b19-f464dde9e72a.png)

![Bildschirmfoto_2021-10-02_19-34-45](https://user-images.githubusercontent.com/79079633/135727022-1102232d-d5ff-431d-a5d1-9178a4defd91.png)

### ... but here I must kill the installation with my task-manager, because the installer hangs up!

![Bildschirmfoto_2021-10-02_19-40-35](https://user-images.githubusercontent.com/79079633/135727026-3021d26a-92fb-4039-b9c6-202184e192c1.png)

### ... and then I have restarted the installation and I was able to continue! 😀

https://user-images.githubusercontent.com/79079633/135727119-e8e3a84b-7f47-4ff8-a465-83e502499071.mp4

**Comment by Shadow-Hunt3r** [comment]
I know this issue is closed but does anyone know how to solve solidworks soft crashing whenever i put in the serial code on my end? (ーー; )

**Comment by orabeidm** [comment]
I'm not that good at linux and I need help with step-by-step instructions.

**Comment by lhow** [comment]
Is the question about using SolidWorks in Linux still going on? The documentation is based on Wine 6.x. Wine 9.x is already in use.

**Comment by orabeidm** [comment]
I tried to install it recently, but it didn't work out.

**Comment by Meenya** [comment]
Hi. Do not install Solidworks from external or flash drive. Copy installation files directly to C drive. It works for me.
