### ISSUE TITLE
SOLIDWORKS somewhat installed but cannot verify serial number

### ISSUE THREAD

**Issue by Duedot43** [cryinkfly/SOLIDWORKS-Linux-Wine-Version-#9]
![image](https://user-images.githubusercontent.com/75505449/133367894-b8cb7ea3-8995-451b-ae36-f14e43544212.png)
I somewhat got SOLIDWORKS to install I used the dev version downloaded the install files as per the usual hung at installing VBA killed sldim went to the downloaded content thing tried manual install it failed launched sldworks.exe and it came up with this any ideas on how to fix it?

**Comment by Duedot43** [comment]
got past that screen by just launching it again now requesting activation from solidworks

**Comment by Duedot43** [comment]
SOLIDWORKS has been successfully licenced and attempts to launch but comes up with this error
![image](https://user-images.githubusercontent.com/75505449/133369634-bfc1b01e-175f-44b8-b2b8-93345bf45668.png)

**Comment by qwertychouskie** [comment]
Maybe `winetricks dotnet48` in the prefix would help, since the crash is related to `mscoree`?

**Comment by Duedot43** [comment]
says its broken on the latest wine version but I'm gonna try it anyway

**Comment by qwertychouskie** [comment]
Should work as long as your Wine is 6.7 or above.  https://github.com/Winetricks/winetricks/blob/master/src/winetricks#L9710

**Comment by Duedot43** [comment]
its saying starting SOLIDWORKS with the older wine version I'm using the flatpak proton version in the dev script I will give it a few minutes to launch because of my slow computer

**Comment by Duedot43** [comment]
SOLIDWORKS successfully launches the first time but not a second I have to install (please wait) again for it to launch

**Comment by cryinkfly** [comment]
It could be that it has to be installed a second time with the --force option.

Fore example: winetricks -q --force dotnet48

**Comment by Duedot43** [comment]
That's the only way I could install it with just flatpak run (proton thing don't remember the name at the moment) winetricks -q dotnet48 it says the wine version is too old and won't work so it makes me use the --force to install it

**Comment by Duedot43** [comment]
steps on how I install it for anyone who needs it:
run the latest dev release 
dev release drops outrun the portion of the code that goes into flatpak proton bash shell 


cd $HOME &&
cd Downloads &&
mkdir -p solidworks &&
cd solidworks &&
wget https://dl-ak.solidworks.com/nonsecure/sw2020/sw2020_sp04.0_f/x64/200715.002-1-QA7UDVC9/SolidWorksSetup.exe &&


wine SolidWorksSetup.exe


download and attempt an install 
install hangs at installing VBA
killall sldim.exe
run setup.exe from downloaded files (SOLIDWORKS-Downloads/SOLIDWORKS-2020-SP04/swwi/data/setup.exe)
install solidworks standard 
install fails
open sldworks.exe from the attempted install folder and should come up with an error with verifying the key
open sldworks.exe again from the attempted install folder and REGISTER THE PRODUCT crashes with error when launching with flatpak proton
run flatpak run org.winehq.flatpak-proton-68-ge-1 winetricks -q --force dotnet48
launch sldworks.exe again and this time it should launch successfully 

note:ALWAYS USE FLATPAK PROTON FROM THE DEV RELESE TO LAUNCH EXE FILES and run in the default bottle

**Comment by Duedot43** [comment]
A few notes about using solidworks it can't find its toolbox folder and it's fonts are kind of messed up they appear then slowly dissipate and if you switch windows while smart dimension is loading it's little window prompt it will freeze and crash￼
